#Azure Server Configuration
azure:
  activedirectory:
    client-id: 2a285aa4-649e-4dd0-b856-b29a2ff46f9d
    client-secret: IwI8Q~BrxM2VyTht-jSnzwABb~x4LHDuzTvhvcpC
    app-id-uri: http://localhost
    tenant-id: a42e43e2-c7b8-499c-89a6-4b9bac2d5a6e
authorization-clients:
  graph:
    scopes:
      - https://graph.microsoft.com/User.Read
logging:
  level:
    org:
      springframework:
        security: TRACE
    com:
      azure:
        spring: TRACE